spring:
  application:
    name: gitscorer
  threads:
    virtual:
      enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      github-api-client:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3

github:
  api:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}

weights:
  stars: 1
  forks: 1
  mostRecentUpdates: 2

topNToReturn: 10
pageLimit: 10

